version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-apache
    container_name: API
    volumes:
      - ./api:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    ports:
      - "8081:80"
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 132490Kj@br=
      MYSQL_DATABASE: sistema_licenca
      MYSQL_USER: n3rdy
      MYSQL_PASSWORD: N3rdygamerbr@123
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
